spring:
  profiles:
     active: dev
  thymeleaf:
      cache: false  
  mapper: 
     plugin: tk.mybatis.mapper.generator.MapperPlugin
     Mapper: com.util.CustomerMapper
  datasource: 
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
#JWT配置
jwt:
  ##认证名称
  header: authorization
  ##过期时间一天(秒)
  expiration: 86400
  ##Tokenu前缀
  token:
    head: Bearer
  ##加密向量
  secret: 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
#mybatis: 
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: mybatis/**/*Mapper.xml
#   mapper-locations: mybatis/mapper/*.xml          