server:
  port: 8085
logging:
  level:
    root: info
    com: debug  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaoan?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
